### PR TITLE
yt scipy tutorial 2020

### PR DESCRIPTION
**Pull request by munkm**
Here's a first stab at our tutorial. I didn't flesh out what the second half will be more specifically, and I'd like to think of data other than IsolatedGalaxy to use (ideally from other domains). LMK what you think.

### CODE REVIEW

**Comment by munkm** [comment]
The short description should be rewritten. It's going to be posted on the scipy website so potential audience members will choose the tutorials they want to attend by looking at this. I think we should probably revise it to be a series of questions about common pre-yt-discovery problems that scientists might have (e.g. "Did you find it hard to slice through your mesh-based data effectively?").

**Review by matthewturk — APPROVED** [review]
this looks amazing

**Comment by Xarthisius** [comment]
Looks great! I'd mention that we might provide remote environment if necessary with yt and data (either hub.yt or WT depending on the interest)
I also found a couple of typos, can I push directly to this branch?

**Comment by munkm** [comment]
@Xarthisius please go ahead and push. If you'd like to help rewrite the short section that would also be great. 

I was thinking it'd be awesome if we could do it all through WT. But then I remembered that there are sometimes issues with internet at SciPy, especially the tutorials. Or am I misremembering that?

**Pull request merged**
