### PR TITLE
SciPy Poster Abstract

### PR DESCRIPTION
**Pull request by samwalkow**
SciPy Poster Abstract on yt, domain storytelling and developing a domain specific langauge.

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]
I like this, but I also think we should be prepared for it to be declined for being too science-y and not python-y enough.  And, that would be OK!  But I want to prep for that possibility.  @munkm any thoughts?

**Comment by samwalkow** [comment]
It was hard to be specific about python implementation. I was going to mention using metadsl (https://metadsl.readthedocs.io/en/latest/) or other libraries but I realized we hadn't actually decided to use anything specific.

**Comment by matthewturk** [comment]
Right, and again, this is not a *knock*.

**Comment by samwalkow** [comment]
I didn't think it was! But I'm aware this is a more academic direction. If we want to change tracks completely, I could write something up about the analysis schema work we did last semester?

**Comment by matthewturk** [comment]
Nah, I think it's good.

**Review by munkm — APPROVED** [review]
I think this looks great! It might be a bit academic, but especially if you're aiming for a poster session I think this is appropriate. I have a few comments, but if you feel they modify the narrative of your submission too much then feel free to disregard. 

* I would try to highlight that this grammar is meant to help split the domain specific language from the generic underlying data structures that may represent the data a bit earlier in the long abstract. I might even be specific with examples here (e.g. hubble constant for a domain specific piece of information vs. mesh spacing for a domain general piece of information). I suspect many of your reviewers will not be familiar with the language you're using here so grounding it in examples of what they know will help contextualize it. You do say something about this in the final paragraph, but I would add a sentence somewhere in the second paragraph (maybe right after "The JSON schema is designed to be a fluid mental model within the software.". This adds the motivation of why a bit earlier and will give the readers a lens through which to review the rest of the paper. 

In your second paragraph you say 

> This exponential growth has diversified the ecosystem but also narrowed the scope of the tools themselves. We see new domain specific tools emerge and existing tools start to stagnate, or disappear completely. Despite overlapping functionality and purpose, open source scientific libraries face difficulty attracting and keeping contributors for exiting tools.

I might revise this slightly. yt has growing pains, but there are some packages that have been around for a long time in the scipy stack that are unlikely to be replaced with newer, lighter tools (matplotlib, numpy, scipy) even though they have a lot of legacy design choices and may be more monolithic than newer tools.  

> In an effort to both harness and counter this exponential growth,

I might also revise this to "counter the challenges yt has experienced with this technical growth", so it's clear we aren't trying to stagnate growth, but address the challenges that exist for us as a result of it. 

* Another great feature of this schema is that it will allow for domain scientists to contribute while also (hopefully) minimally interacting with the generic tools that are backing all of their data. That should help a larger group of people to contribute to the software while also lowering the barriers of contribution that exist currently in our codebase. You may want to mention the benefits of this schema more generally to help motivate the work too.

**Comment by samwalkow** [comment]
Thanks @munkm, I'll keep working on it.

**Comment by munkm** [comment]
🙌 🎈 🐍

**Pull request merged**
